apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-deployment-init-configmap
data:
  mariadb-init.sql: |
    CREATE TABLE `netflix_titles` (
      `show_id`     VARCHAR(5)    NOT NULL,
      `title`       VARCHAR(150)  NOT NULL,
      `director`    VARCHAR(50),
      `cast`        VARCHAR(1000),
      `country`     VARCHAR(100),
      `release_year` INT,
      `duration`    VARCHAR(20),
      `genre`       VARCHAR(100),
      `description` VARCHAR(300),

      PRIMARY KEY (`show_id`)
    );

    CREATE TABLE `rating` (
      `show_id` VARCHAR(5)  NOT NULL,
      `rating`  INT,

      PRIMARY KEY (`show_id`)
    );


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: my-mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mariadb
  template:
    metadata:
      labels:
        app: my-mariadb
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      volumes:
        - name: init-volume
          configMap:
            name: mariadb-deployment-init-configmap
      containers:
        - name: my-mariadb
          image: mariadb:10.7.4
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: "mysecretpw"
            # - name: MARIADB_PASSWORD
            #   value: "mysecretpw"
            - name: MARIADB_DATABASE
              value: "popular"

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mariadb-service
spec:
  selector:
    app: my-mariadb
  ports:
    - name: mariadb-proto
      protocol: TCP
      port: 3306
      targetPort: 3306
#End: Service
